
services:
  keycloak: # https://hub.docker.com/r/bitnami/keycloak
    image: quay.io/keycloak/keycloak
    restart: always
    command: start
    volumes:
      - /etc/letsencrypt/live/francl.in/privkey.pem:/opt/keycloak/data/privkey.pem:ro
      - /etc/letsencrypt/live/francl.in/fullchain.pem:/opt/keycloak/data/fullchain.pem:ro
    healthcheck:
      test: 
        - CMD-SHELL
        - curl
        - -f
        - https://localhost:9000/health
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 30s
    networks:
      database:
      iam:
        aliases:
          - keycloak
      gateway:
        aliases:
          - keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/data/privkey.pem
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/data/fullchain.pem
      KC_HEALTH_ENABLED: true
      KC_FEATURES: account-api:v1,account:v3,admin-api:v1,admin:v2,authorization:v1,ciba:v1,client-policies:v1,device-flow:v1,docker:v1,hostname:v2,impersonation:v1,kerberos:v1,login:v2,multi-site:v1,organization:v1,par:v1,persistent-user-sessions:v1,preview,step-up-authentication:v1,web-authn:v1
    deploy:
      mode: global
      resources:
        limits:
          cpus: '1'
          memory: 1024M
      restart_policy:
        condition: on-failure

networks:
  iam:
    name: iam
    attachable: true
    enable_ipv6: true
  gateway:
    external: true
    enable_ipv6: true
  database:
    external: true
    enable_ipv6: true

volumes:
  keycloak:
    name: keycloak
