
services:
  keycloak: # https://hub.docker.com/r/bitnami/keycloak
    image: keycloak/keycloak
    command: start --verbose --log-level="org.keycloak.broker.oidc:DEBUG,org.keycloak.broker.provider:DEBUG"
    volumes:
      - /etc/letsencrypt/live/francl.in:/etc/letsencrypt/live/francl.in:ro
      - /etc/letsencrypt/archive/francl.in:/etc/letsencrypt/archive/francl.in:ro
    networks:
      database:
      iam:
        aliases:
          - keycloak
      gateway:
        aliases:
          - keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/letsencrypt/live/francl.in/privkey.pem
      KC_HTTPS_CERTIFICATE_FILE: /etc/letsencrypt/live/francl.in/fullchain.pem
      KC_HEALTH_ENABLED: true
      KC_PROXY_HEADERS: xforwarded
      KC_FEATURES: account-api:v1,account:v3,admin-api:v1,admin:v2,authorization:v1,ciba:v1,client-policies:v1,device-flow:v1,docker:v1,hostname:v2,impersonation:v1,login:v2,token-exchange:v1,organization:v1,par:v1,persistent-user-sessions:v1,step-up-authentication:v1,web-authn:v1
    deploy:
      mode: global
      resources:
        limits:
          cpus: '1'
          memory: 1024M
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

networks:
  iam:
    name: iam
    attachable: true
    enable_ipv6: true
  gateway:
    external: true
    enable_ipv6: true
  database:
    external: true
    enable_ipv6: true

volumes:
  keycloak:
    name: keycloak
